#!/bin/bash

#SBATCH -J spatial_results
#SBATCH -o spatial_%j.txt
#SBATCH -e spatial_%j.err
#SBATCH -p largememory
#SBATCH --mail-type=ALL
#SBATCH --mail-user=whitealj@iu.edu
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=48
#SBATCH --mem=500G
#SBATCH --time=168:00:00

module load r/4.0.4

cd "/geode2/home/u100/whitealj/Carbonate/scripts/"
R CMD BATCH "/geode2/home/u100/whitealj/Carbonate/scripts/20210924_spatiallibd.R"