# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fct_c_opt_adam <- function(gradients, state) {
    .Call(`_spatialr_dev_fct_c_opt_adam`, gradients, state)
}

pdist <- function(x, w, index) {
    .Call(`_spatialr_dev_pdist`, x, w, index)
}

fct_c_optimize <- function(x, u, v, w, index, lambda, epsilon, maxiter, display_progress = TRUE) {
    .Call(`_spatialr_dev_fct_c_optimize`, x, u, v, w, index, lambda, epsilon, maxiter, display_progress)
}

obs_log_like <- function(test_x, u, v, test_nn, index_map) {
    .Call(`_spatialr_dev_obs_log_like`, test_x, u, v, test_nn, index_map)
}

